api_platform:
    title: Url shortening service
    version: 1.0.0
    mapping:
        paths: ['%kernel.project_dir%/src/Document']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    doctrine:
        enabled: false
    doctrine_mongodb_odm:
        enabled: true
    mercure:
        enabled: false
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    show_webby: false
    path_segment_name_generator: 'api_platform.path_segment_name_generator.underscore'
